Add CI for developer environments (#983)
* Add CI for developper environments

* Looks needed to be renamed in nix-build

```
Run nix-build
  nix-build
  shell: /usr/bin/bash -e {0}
  env:
    NIX_PATH: nixpkgs=https://github.com/NixOS/nixpkgs/archive/f3f15fa73ddf15fa66cc4f80cda4c5afb356306b.tar.gz
error: getting status of /home/runner/work/renovate-config-asdf/renovate-config-asdf/default.nix: No such file or directory
```

* Try same nixpath of https://github.com/kachick/nix-headbump/blob/5397040c4b62289112c799acfa1fd7613053cb12/default.nix#L1

* Relax CI versions