Looks needed to be renamed in nix-build
```
Run nix-build
  nix-build
  shell: /usr/bin/bash -e {0}
  env:
    NIX_PATH: nixpkgs=https://github.com/NixOS/nixpkgs/archive/f3f15fa73ddf15fa66cc4f80cda4c5afb356306b.tar.gz
error: getting status of /home/runner/work/renovate-config-asdf/renovate-config-asdf/default.nix: No such file or directory
```